<a href="https://colab.research.google.com/github/WenluXu/Data-Science-Bootcamp-2022/blob/main/Week2_Data_Wrangling_Libraries_to_share.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The Basics of NumPy amd Pandas

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas are built around the NumPy array.
This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.
While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples used throughout the book.
Get to know them well!

We'll cover a few categories of basic array manipulations here:

- Understanding Numpy*: Creating very basic arrays.
- *Attributes of arrays*: Determining the size, shape, memory consumption, and data types of arrays
- *Indexing of arrays*: Getting and setting the value of individual array elements
- *Slicing of arrays*: Getting and setting smaller subarrays within a larger array
- *Reshaping of arrays*: Changing the shape of a given array
- *Joining and splitting of arrays*: Combining multiple arrays into one, and splitting one array into many

## NumPy Array Attributes

First let's discuss some useful array attributes.
We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array.
We'll use NumPy's random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [ ]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Another useful attribute is the ``dtype``

In [ ]:
print("dtype:", x3.dtype)

dtype: int64


Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In general, we expect that ``nbytes`` is equal to ``itemsize`` x ``size``.

## Array Indexing: Accessing Single Elements

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0]

In [ ]:
x1[4]

To index from the end of the array, you can use negative indices:

In [ ]:
x1[-1]

In [ ]:
x1[-2]

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [ ]:
x2

In [ ]:
x2[0, 0]

In [ ]:
x2[2, 0]

In [ ]:
x2[2, -1]

In [ ]:
x2[1]

array([7, 6, 8, 8])

Values can also be modified using any of the above index notation:

In [ ]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [ ]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [ ]:
x[5:]  # elements after index 5

In [ ]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [ ]:
x[::2]  # every other element

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
x[1::2]  # every other element, starting at index 1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [ ]:
x[::-1]  # all elements, reversed

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [ ]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [ ]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x2[:2, :3]  # two rows, three columns

In [ ]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Finally, subarray dimensions can even be reversed together:

In [ ]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [ ]:
print(x2[:, 0])  # first column of x2

[12  7  1]


In [ ]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [ ]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [ ]:
print(x2)

Let's extract a $2 \times 2$ subarray from this:

In [ ]:
x2_sub = x2[:2, :2]
print(x2_sub)

Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [ ]:
x2_sub[0, 0] = 99
print(x2_sub)

In [ ]:
print(x2)

This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [ ]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

If we now modify this subarray, the original array is not touched:

In [ ]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

In [ ]:
print(x2)

## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [ ]:
grid = np.arange(1, 19).reshape((3, 6))
print(grid)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


Note that for this to work, the size of the initial array must match the size of the reshaped array.
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [ ]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [ ]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [ ]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [ ]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

We will see this type of transformation often throughout the remainder of the book.

## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [ ]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


It can also be used for two-dimensional arrays:

In [ ]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [ ]:
# concatenate along the first axis
new_grid=np.concatenate([grid, grid])
print(new_grid)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [ ]:
# concatenate along the second axis (zero-indexed)
new_grid= np.concatenate([grid, grid], axis=1)
new_grid.shape

(2, 6)

For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
# horizontally stack the arrays
y = np.array([[99,98],
              [99,33]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99, 98],
       [ 6,  5,  4, 99, 33]])

Similary, ``np.dstack`` will stack arrays along the third axis.

### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 ,x4= np.split(x, [3, 5,6])
print(x1, x2, x3,x4)

[1 2 3] [99 99] [3] [2 1]


Notice that *N* split-points, leads to *N + 1* subarrays.
The related functions ``np.hsplit`` and ``np.vsplit`` are similar:

In [ ]:
grid = np.arange(1,17).reshape((4, 4))
grid

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


Similarly, ``np.dsplit`` will split arrays along the third axis.

In [ ]:
x = np.arange(16.0).reshape(2, 2, 4)
print(x)
np.dsplit(x, 2)

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]]

 [[ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]]


[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]), array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

In [ ]:
np.dsplit(x, np.array([3, 6]))

[array([[[ 0.,  1.,  2.],
         [ 4.,  5.,  6.]],
 
        [[ 8.,  9., 10.],
         [12., 13., 14.]]]), array([[[ 3.],
         [ 7.]],
 
        [[11.],
         [15.]]]), array([], shape=(2, 2, 0), dtype=float64)]

## Starting with Pandas

Pandas is a library written in python for doing data manipulation. Data manipulation means to create, delete, and update the data.

It is one of the most commonly used libraries when doing data analysis and manipulation in python. It offers data structures and operations for manipulating numerical tables and time series. It presents a diverse range of utilities, ranging from parsing multiple file-formats to converting an entire data table into a Numpy matrix array.


In [ ]:
#we start from the very basics...import...!!!

import pandas as pd
import numpy as np

## PART 1: Getting and Knowing your Data


In [ ]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

chipo = pd.read_csv(url, sep='\t')

### See the first 10 entries

In [ ]:
chipo.head(10)

### Print the last elements of the data set.

In [ ]:
chipo.tail()

order_id  quantity           item_name  \
4617      1833         1       Steak Burrito   
4618      1833         1       Steak Burrito   
4619      1834         1  Chicken Salad Bowl   
4620      1834         1  Chicken Salad Bowl   
4621      1834         1  Chicken Salad Bowl   

                                     choice_description item_price  
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75   
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75   
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25   
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75   
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75

### What is the number of observations in the dataset?

In [ ]:
chipo.shape[0]

4622

### Another way

In [ ]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   order_id            4622 non-null   int64 
 1   quantity            4622 non-null   int64 
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB


### What is the number of columns in the dataset?

In [ ]:
chipo.shape[1]

5

In [ ]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [ ]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### How many items were orderd in total?

In [ ]:
total_items_orders = chipo.quantity.sum()
total_items_orders

4972

### Check the item price type

In [ ]:
chipo.item_price.dtype

dtype('O')

In [ ]:
price = chipo['item_price'].value_counts().count()
price

78

How much was the revenue for the period in the dataset?

In [ ]:
price = chipo.item_price[:]
res = [eval(i[1:]) for i in price]

In [ ]:
revenue = (chipo['quantity']* res)
revenue = revenue.sum()

print('Revenue was: $' + str(np.round(revenue,2)))

Revenue was: $39237.02


In [ ]:
revenue = (chipo['quantity']* chipo['item_price'])
revenue = revenue.sum()

print('Revenue was: $' + str(np.round(revenue,2)))

UFuncTypeError: ignored

How many orders were made in the period?

In [ ]:
orders = chipo.order_id.value_counts().count()
orders

1834

### How many different items are sold?


In [ ]:
chipo.item_name.value_counts().count()


50

## PART B: Filtering and Sorting Data

### What is the price of each item?


In [ ]:
chipo[(chipo['item_name'] == 'Chicken Bowl') & (chipo['quantity'] == 2)]

order_id  quantity     item_name  \
4            2         2  Chicken Bowl   
154         70         2  Chicken Bowl   
282        124         2  Chicken Bowl   
415        181         2  Chicken Bowl   
654        271         2  Chicken Bowl   
976        401         2  Chicken Bowl   
1017       418         2  Chicken Bowl   
1106       457         2  Chicken Bowl   
1429       578         2  Chicken Bowl   
1588       643         2  Chicken Bowl   
1832       741         2  Chicken Bowl   
2075       837         2  Chicken Bowl   
2106       848         2  Chicken Bowl   
2339       932         2  Chicken Bowl   
2510       997         2  Chicken Bowl   
2525      1004         2  Chicken Bowl   
2580      1023         2  Chicken Bowl   
2771      1100         2  Chicken Bowl   
2942      1170         2  Chicken Bowl   
3080      1227         2  Chicken Bowl   
3133      1249         2  Chicken Bowl   
3151      1257         2  Chicken Bowl   
3423      1374         2  Chicken Bowl   
3508      1410         2  Chicken Bowl   
3612      1447         2  Chicken Bowl   
3618      1449         2  Chicken Bowl   
3663      1465         2  Chicken Bowl   
3843      1540         2  Chicken Bowl   
3976      1593         2  Chicken Bowl   
4423      1764         2  Chicken Bowl   
4435      1767         2  Chicken Bowl   

                                     choice_description item_price  
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
154   [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $17.50   
282   [Fresh Tomato Salsa, [Rice, Black Beans, Chees...    $17.50   
415                         [Tomatillo Red Chili Salsa]    $17.50   
654   [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $17.50   
976   [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $17.50   
1017  [Fresh Tomato Salsa, [Rice, Cheese, Black Beans]]    $17.50   
1106  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $17.50   
1429  [Fresh Tomato Salsa, [Rice, Sour Cream, Guacam...    $22.50   
1588  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $17.50   
1832  [Tomatillo-Red Chili Salsa (Hot), [Sour Cream,...    $21.96   
2075  [Tomatillo-Red Chili Salsa (Hot), [Pinto Beans...    $21.96   
2106  [Fresh Tomato Salsa, [Black Beans, Cheese, Sou...    $17.50   
2339  [[Fresh Tomato Salsa (Mild), Roasted Chili Cor...    $16.98   
2510  [Roasted Chili Corn Salsa, [Rice, Black Beans,...    $22.50   
2525  [Tomatillo-Red Chili Salsa (Hot), [Rice, Fajit...    $21.96   
2580  [[Roasted Chili Corn Salsa (Medium), Fresh Tom...    $16.98   
2771  [[Roasted Chili Corn Salsa (Medium), Fresh Tom...    $16.98   
2942  [Tomatillo-Green Chili Salsa (Medium), [Black ...    $21.96   
3080  [[Roasted Chili Corn Salsa (Medium), Fresh Tom...    $16.98   
3133  [[Fresh Tomato Salsa (Mild), Roasted Chili Cor...    $16.98   
3151  [Tomatillo-Red Chili Salsa (Hot), [Pinto Beans...    $21.96   
3423  [Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...    $17.50   
3508  [Tomatillo-Red Chili Salsa (Hot), [Pinto Beans...    $21.96   
3612  [Tomatillo-Red Chili Salsa (Hot), [Cheese, Sou...    $16.98   
3618  [Fresh Tomato Salsa (Mild), [Black Beans, Rice...    $16.98   
3663  [[Roasted Chili Corn Salsa (Medium), Fresh Tom...    $16.98   
3843  [Tomatillo-Red Chili Salsa (Hot), [Rice, Pinto...    $21.96   
3976  [[Roasted Chili Corn Salsa (Medium), Fresh Tom...    $16.98   
4423  [Fresh Tomato Salsa, [Rice, Fajita Vegetables,...    $22.50   
4435  [Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...    $17.50

### Sort by the name of the item

In [ ]:
chipo.item_name.sort_values()

3389    6 Pack Soft Drink
341     6 Pack Soft Drink
1849    6 Pack Soft Drink
1860    6 Pack Soft Drink
2713    6 Pack Soft Drink
              ...        
2384    Veggie Soft Tacos
781     Veggie Soft Tacos
2851    Veggie Soft Tacos
1699    Veggie Soft Tacos
1395    Veggie Soft Tacos
Name: item_name, Length: 4622, dtype: object

### OR

In [ ]:
chipo.sort_values(by = "item_name")


order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
...        ...       ...                ...   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description item_price  
3389                                        [Diet Coke]    $12.98   
341                                         [Diet Coke]     $6.49   
1849                                             [Coke]     $6.49   
1860                                        [Diet Coke]     $6.49   
2713                                             [Coke]     $6.49   
...                                                 ...        ...  
2384  [Roasted Chili Corn Salsa, [Fajita Vegetables,...     $8.75   
781   [Fresh Tomato Salsa, [Black Beans, Cheese, Sou...     $8.75   
2851  [Roasted Chili Corn Salsa (Medium), [Black Bea...     $8.49   
1699  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $11.25   
1395  [Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...     $8.49   

[4622 rows x 5 columns]

### What was the quantity of the most expensive item ordered?

In [ ]:
chipo.sort_values(by = "item_price", ascending = False).head(5)

order_id  quantity            item_name  \
2624      1042         1     Steak Salad Bowl   
4419      1762         1     Steak Salad Bowl   
4036      1615         1     Steak Salad Bowl   
1825       738         1  Barbacoa Salad Bowl   
3115      1243         1  Carnitas Salad Bowl   

                                     choice_description item_price  
2624  [Fresh Tomato Salsa, [Black Beans, Sour Cream,...     $9.39   
4419  [Roasted Chili Corn Salsa, [Fajita Vegetables,...     $9.39   
4036  [Fresh Tomato Salsa, [Fajita Vegetables, Chees...     $9.39   
1825  [Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...     $9.39   
3115  [Tomatillo Green Chili Salsa, [Rice, Pinto Bea...     $9.39

### How many times was a Veggie Salad Bowl ordered?

In [ ]:
chipo_salad = chipo[chipo.item_name == "Veggie Salad Bowl"]
print(chipo_salad)
len(chipo_salad)

      order_id  quantity          item_name  \
186         83         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
4201      1677         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   

                                     choice_description item_price  
186   [Fresh Tomato Salsa, [Fajita Ve

18

### Trying some different dataset

In [ ]:
drinks = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv')
drinks.head()

country  beer_servings  spirit_servings  wine_servings  \
0  Afghanistan              0                0              0   
1      Albania             89              132             54   
2      Algeria             25                0             14   
3      Andorra            245              138            312   
4       Angola            217               57             45   

   total_litres_of_pure_alcohol continent  
0                           0.0        AS  
1                           4.9        EU  
2                           0.7        AF  
3                          12.4        EU  
4                           5.9        AF

### Which continent drinks more beer on average?

In [ ]:
drinks.groupby('continent').beer_servings.mean()

continent
AF     61.471698
AS     37.045455
EU    193.777778
OC     89.687500
SA    175.083333
Name: beer_servings, dtype: float64

### For each continent print the statistics for wine consumption.

In [ ]:
drinks.groupby('continent').wine_servings.describe()

count        mean        std  min   25%    50%     75%    max
continent                                                               
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

### Print the median alcohol consumption per continent for every column

In [ ]:
drinks.groupby('continent').mean()

beer_servings  spirit_servings  wine_servings  \
continent                                                  
AF             61.471698        16.339623      16.264151   
AS             37.045455        60.840909       9.068182   
EU            193.777778       132.555556     142.222222   
OC             89.687500        58.437500      35.625000   
SA            175.083333       114.750000      62.416667   

           total_litres_of_pure_alcohol  
continent                                
AF                             3.007547  
AS                             2.170455  
EU                             8.617778  
OC                             3.381250  
SA                             6.308333

### Print the median alcohol consumption per continent for every column


In [ ]:
drinks.groupby('continent').median()

beer_servings  spirit_servings  wine_servings  \
continent                                                  
AF                  32.0              3.0            2.0   
AS                  17.5             16.0            1.0   
EU                 219.0            122.0          128.0   
OC                  52.5             37.0            8.5   
SA                 162.5            108.5           12.0   

           total_litres_of_pure_alcohol  
continent                                
AF                                 2.30  
AS                                 1.20  
EU                                10.00  
OC                                 1.75  
SA                                 6.85

### Print the mean, min and max values for spirit consumption.

In [ ]:
drinks.groupby('continent').spirit_servings.agg(['mean', 'min', 'max'])

mean  min  max
continent                      
AF          16.339623    0  152
AS          60.840909    0  326
EU         132.555556    0  373
OC          58.437500    0  254
SA         114.750000   25  302

### Trying some more different functionalities

In [ ]:
csv_url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/Students_Alcohol_Consumption/student-mat.csv'
df = pd.read_csv(csv_url)
stud_alcoh = df.loc[: , "school":"guardian"]
stud_alcoh.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher   
1     GP   F   17       U     GT3       T     1     1  at_home     other   
2     GP   F   15       U     LE3       T     1     1  at_home     other   
3     GP   F   15       U     GT3       T     4     2   health  services   
4     GP   F   16       U     GT3       T     3     3    other     other   

   reason guardian  
0  course   mother  
1  course   father  
2   other   mother  
3    home   mother  
4    home   father

In [ ]:
addition_fun = lambda a:a+5

v = addition_fun(10)
v

15

In [ ]:
capitalizer = lambda x: x.capitalize()


In [ ]:
stud_alcoh['Mjob'].apply(capitalizer)
stud_alcoh['Fjob'].apply(capitalizer)
stud_alcoh.tail()

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     reason guardian  
390  course    other  
391  course   mother  
392  course    other  
393  course   mother  
394  course   father

In [ ]:
stud_alcoh['Mjob'] = stud_alcoh['Mjob'].apply(capitalizer)
stud_alcoh['Fjob'] = stud_alcoh['Fjob'].apply(capitalizer)
stud_alcoh.tail()

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
390     MS   M   20       U     LE3       A     2     2  Services  Services   
391     MS   M   17       U     LE3       T     3     1  Services  Services   
392     MS   M   21       R     GT3       T     1     1     Other     Other   
393     MS   M   18       R     LE3       T     3     2  Services     Other   
394     MS   M   19       U     LE3       T     1     1     Other   At_home   

     reason guardian  
390  course    other  
391  course   mother  
392  course    other  
393  course   mother  
394  course   father

### Here instead of just using the existing the data, we will create our own dataframe/dataseries

In [ ]:
a = pd.Series([1,2,3])
a

0    1
1    2
2    3
dtype: int64

In [ ]:
print('Data passed as a list')
df_list = pd.DataFrame([['May1', 32], ['May2', 35], ['May3', 40], ['May4', 50]])
print(df_list)

Data passed as a list
      0   1
0  May1  32
1  May2  35
2  May3  40
3  May4  50


In [ ]:
print('Data passed as dictionary')
df_dict = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]},dtype = float)
print(df_dict)

Data passed as dictionary
     A    B
0  1.0  4.0
1  2.0  5.0
2  3.0  6.0


In [ ]:
# Rename columns

df_dict.rename(columns={'A': 'a'})

# inplace by default is false
# if inplace = True is not set then the changes are not made on the original df but only a temp df is made with changes
df_dict

A    B
0  1.0  4.0
1  2.0  5.0
2  3.0  6.0

In [ ]:
# changes made for original df

df_dict.rename(columns={'A': 'a'}, inplace=True)
df_dict


a    B
0  1.0  4.0
1  2.0  5.0
2  3.0  6.0

In [ ]:
# Reset column names
# Tip: remember to pass the entire list in this case

df_dict.columns = ['a', 'b']
df_dict.head()

a    b
0  1.0  4.0
1  2.0  5.0
2  3.0  6.0

In [ ]:
# Defining columns, index during dataframe creation

df_temp = pd.DataFrame([['October 1', 67], ['October 2', 72], ['October 3', 58], ['October 4', 69], ['October 5', 77]], index = ['Day 1', 'Day 2', 'Day 3', 'Day 4', 'Day 5'], columns = ['Month', 'Temperature'])
df_temp


Month  Temperature
Day 1  October 1           67
Day 2  October 2           72
Day 3  October 3           58
Day 4  October 4           69
Day 5  October 5           77